# Generated by Django 3.0.6 on 2020-07-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewels', '0009_auto_20200713_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En camino', 'En camino'), ('Enviado', 'Enviado')], max_length=200, null=True),
        ),
    ]
