# Generated by Django 3.0.6 on 2020-07-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewels', '0010_auto_20200713_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
