# Generated by Django 3.0.6 on 2020-07-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewels', '0011_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='units',
            field=models.IntegerField(null=True),
        ),
    ]
