# Generated by Django 3.0.6 on 2020-07-18 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewels', '0012_product_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Pulsera', 'Pulsera'), ('Collar', 'Collar'), ('Gemelos', 'Gemelos'), ('Anillo', 'Anillo'), ('Llavero', 'Llavero'), ('Pendientes', 'Pendientes'), ('Brazalete', 'Brazalete'), ('Gargantilla', 'Gargantilla'), ('Colgante', 'Colgante'), ('Tobillera', 'Tobillera')], max_length=200, null=True),
        ),
    ]
